#!/bin/bash

if [ "$1" = "build" ] 
	then
	mkdir -p build
	cd build
	cmake ..
	make
elif [ "$1" = "start" ] 
	then
	cd build
	./func_opt_o
elif [ "$1" = "clean" ]
	then
	rm -rf build/* 
elif [ "$1" = "" ]
	then
	mkdir -p build
	cd build
	cmake ..
	make
	./func_opt_o
elif [ "$1" = "help" ]
	then
	echo "possible options:"
	echo "	'build' - to build the project"
	echo "	'start' - to run the project"
	echo "	'clean' - to clean the build repository"
	echo "	no parameters - to build and run the project  "
else
	echo "You entered something wrong. Please try with option 'help'"
fi

