/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Binding */

#ifndef _Included_Binding
#define _Included_Binding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Binding
 * Method:    rastrigin_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_rastrigin_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    sphere_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_sphere_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    stibinski_tanga_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_stibinski_1tanga_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    ekli_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_ekli_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    rosenbrock_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_rosenbrock_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    bill_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_bill_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    goldman_price_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_goldman_1price_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    boot_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_boot_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    bookin_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_bookin_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    matias_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_matias_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    levi_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_levi_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    three_hump_camel_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_three_1hump_1camel_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    easom_function
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Binding_easom_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_execution_time
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Binding_get_1execution_1time
  (JNIEnv *, jobject);

/*
 * Class:     Binding
 * Method:    hooke_jeeves_method
 * Signature: ([DLjava/lang/String;[DF)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_hooke_1jeeves_1method
  (JNIEnv *, jobject, jdoubleArray, jstring, jdoubleArray, jfloat);

/*
 * Class:     Binding
 * Method:    luus_jaakola_method
 * Signature: ([DLjava/lang/String;[DF)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_luus_1jaakola_1method
  (JNIEnv *, jobject, jdoubleArray, jstring, jdoubleArray, jfloat);

/*
 * Class:     Binding
 * Method:    competing_points_method
 * Signature: ([DLjava/lang/String;[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_competing_1points_1method
  (JNIEnv *, jobject, jdoubleArray, jstring, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_rastrigin_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1rastrigin_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_sphere_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1sphere_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_stibinski_tanga_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1stibinski_1tanga_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_ekli_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1ekli_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_rosenbrock_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1rosenbrock_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_bill_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1bill_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_goldman_price_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1goldman_1price_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_boot_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1boot_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_bookin_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1bookin_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_matias_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1matias_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_levi_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1levi_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_three_hump_camel_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1three_1hump_1camel_1function
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     Binding
 * Method:    get_min_x_easom_function
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Binding_get_1min_1x_1easom_1function
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
